console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[palette]
black = '#262B44'
blue = '#4B95E9'
green = '#59C9A5'
orange = '#F07623'
red = '#D81E5B'
white = '#E0DEF4'
yellow = '#F3AE35'

[secondary_prompt]
template = '<p:yellow,transparent></><,p:yellow> > </><p:yellow,transparent></> '
foreground = 'p:black'
background = 'transparent'

[transient_prompt]
template = '<p:yellow,transparent></><,p:yellow> {{ .Folder }} </><p:yellow,transparent></> '
foreground = 'p:black'
background = 'transparent'

[upgrade]
source = 'cdn'
interval = '168h'
auto = false
notice = false

[[tooltips]]
leading_diamond = ''
trailing_diamond = ''
template = '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '
foreground = 'p:white'
background = 'p:orange'
type = 'aws'
style = 'diamond'
tips = ['aws']

[tooltips.properties]
display_default = true

[[tooltips]]
leading_diamond = ''
trailing_diamond = ''
template = '  {{ .Name }} '
foreground = 'p:white'
background = 'p:blue'
type = 'az'
style = 'diamond'
tips = ['az']

[tooltips.properties]
display_default = true

[[blocks]]
type = 'prompt'
alignment = 'left'

[[blocks.segments]]
template = '  {{ path .Path .Location }} '
foreground = 'p:white'
# foreground = 'p:black'
# background = 'p:yellow'
leading_diamond = ''
trailing_diamond = ''
# powerline_symbol = ''
background = 'p:orange'
type = 'path'
style = 'diamond'

[blocks.segments.properties]
style = 'folder'

[[blocks.segments]]
template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }} '
foreground = 'p:black'
powerline_symbol = ''
background = 'p:green'
type = 'git'
style = 'powerline'

[blocks.segments.properties]
branch_template = '{{ trunc 25 .Branch }}'
fetch_status = true
fetch_upstream_icon = true

[[blocks.segments]]
template = '  '
foreground = 'p:white'
powerline_symbol = ''
background = 'p:yellow'
type = 'root'
style = 'powerline'

[[blocks.segments]]
leading_diamond = '<transparent,background></>'
trailing_diamond = ''
template = ' {{ if gt .Code 0 }}{{ else }}{{ end }} '
foreground = 'p:white'
background = 'p:blue'
type = 'status'
style = 'diamond'
background_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']

[blocks.segments.properties]
always_enabled = true

[[blocks]]
type = 'rprompt'


[[blocks.segments]]
template = '<p:blue><b>{{ .CurrentDate | date "15:04:05" }}</b></>'
foreground = 'p:white'
background = 'transparent'
type = 'time'
style = 'plain'
