theme = "onedark"

[editor]
line-number = "relative"
scrolloff = 5
cursorline = true
auto-completion = true
auto-format = true
auto-save = true
color-modes = true
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.search]
smart-case = true

[keys.insert.j]
k = "normal_mode"

[keys.insert.k]
j = "normal_mode"
