wsl = false
multigrid = true
vsync = true
maximized = true
srgb = true
idle = true
neovim-bin = "/usr/local/bin/nvim"
# TYPE "TRANSPARENT" | "FULL" | "BUTTONLESS" | "NONE"
frame = "buttonless"
title-hidden = true

[font]
normal = ["Fira Code Retina"]
bold = "Fira Code"
italic = "Maple Mono"
bold_italic = "Maple Mono"
size = 13.5

[font.features]
"Fira Code Retina" = [
  "+ss01",
  "+ss02",
  "+ss03",
  "+ss04",
  "+ss05",
  "+ss07",
  "+ss09",
  "+ss11",
  "+ss14",
  "+ss16",
  "+ss17",
  "cv15",
  "cv16",
  "cv23",
  "cv28",
  "-calt",
  "onum",
]
"Maple Mono" = [
  "+ss01",
  "+ss02",
  "+ss03",
  "+ss04",
  "+ss05",
  "+cv01",
  "+cv02",
  "+cv03",
  "+cv04",
]
