wsl = false
multigrid = true
vsync = true
maximized = true
srgb = true
idle = true
neovim-bin = "/usr/local/bin/nvim"
# TYPE "TRANSPARENT" | "FULL" | "BUTTONLESS" | "NONE"
frame = "buttonless"
title-hidden = true

[box-drawing]
mode = "native" # "font-glyph" | "native" | "selected-native"

[box-drawing.sizes]
default = [2, 6]
12 = [1, 2]
15 = [2,7]
18 = [3, 8]

[font]
size = 15.0

[[font.normal]]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[[font.italic]]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[[font.bold]]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[[font.bold_italic]]
family = "CaskaydiaCove Nerd Font"
style = "SemiBold"

[font.features]
"CaskaydiaCove Nerd Font" = [
  "+ss01",
  "+ss02",
  "+ss03",
  "+ss19",
  "+ss20",
  # other might exist
]
