wsl = false
multigrid = true
vsync = true
maximized = true
srgb = true
idle = true
neovim-bin = "/usr/local/bin/nvim"
# TYPE "TRANSPARENT" | "FULL" | "BUTTONLESS" | "NONE"
frame = "buttonless"
title-hidden = true

[font]
# normal = ["Fira Code Retina"]
# bold = ["Fira Code"]
# italic = "MapleMono-NF-Italic"
# bold_italic = "MapleMono-NF-BoldItalic"
size = 16.0
# width = 0.8

[[font.normal]]
# family = "FiraCode NFM"
family = "CaskaydiaCove Nerd Font Mono"
style = "Normal"

[[font.bold]]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[[font.italic]]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[[font.bold_italic]]
family = "CaskaydiaCove Nerd Font Mono"
style = "BoldItalic"

# [font.features]
# "Fira Code Retina" = [
#   "+ss01",
#   "+ss02",
#   "+ss03",
#   "+ss04",
#   "+ss05",
#   "+ss07",
#   "+ss09",
#   "+ss11",
#   "+ss14",
#   "+ss16",
#   "+ss17",
#   "cv15",
#   "cv16",
#   "cv23",
#   "cv28",
#   "-calt",
#   "onum",
# ]
# "Maple Mono NF" = [
#   "+ss01",
#   "+ss02",
#   "+ss03",
#   "+ss04",
#   "+ss05",
#   "+cv01",
#   "+cv02",
#   "+cv03",
#   "+cv04",
# ]
